name: Publish

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@master


      # Install npm dependencies
      - name: npm install
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{github.token}}
          
          
      # Publish to GitHub Package Registry
      - uses: actions/setup-node@master
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/@soroushchehresa
          scope: '@soroushchehresa'
      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{github.token}}
